Organizations:
  - &OrdererOrg
    Name: Orderer
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/ifmprofile-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"

  - &usb
    Name: usbMSP
    ID: usbMSP
    MSPDir: crypto-config/peerOrganizations/usb.ifmprofile-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('usbMSP.admin', 'usbMSP.peer', 'usbMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('usbMSP.admin', 'usbMSP.peer', 'usbMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('usbMSP.admin', 'usbMSP.peer', 'usbMSP.client')"
    AnchorPeers:
      - Host: peer0.usb.ifmprofile-network.com
        Port: 7051

  - &jpmc
    Name: jpmcMSP
    ID: jpmcMSP
    MSPDir: crypto-config/peerOrganizations/jpmc.ifmprofile-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('jpmcMSP.admin', 'jpmcMSP.peer', 'jpmcMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('jpmcMSP.admin', 'jpmcMSP.peer', 'jpmcMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('jpmcMSP.admin', 'jpmcMSP.peer', 'jpmcMSP.client')"
    AnchorPeers:
      - Host: peer0.jpmc.ifmprofile-network.com
        Port: 9051

  - &boa
    Name: boaMSP
    ID: boaMSP
    MSPDir: crypto-config/peerOrganizations/boa.ifmprofile-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('boaMSP.admin', 'boaMSP.peer', 'boaMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('boaMSP.admin', 'boaMSP.peer', 'boaMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('boaMSP.admin', 'boaMSP.peer', 'boaMSP.client')"
    AnchorPeers:
      - Host: peer0.boa.ifmprofile-network.com
        Port: 11051



#Capabilities

Capabilities:
  Channel: &ChannelCapabilities
    V1_4_3: true
    V1_3: false
    V1_1: false
  Orderer: &OrdererCapabilities
    V1_4_2: true
    V1_1: false
  Application: &ApplicationCapabilities
    V1_4_2: true
    V1_3: false
    V1_2: false
    V1_1: false

#Application

Application: &ApplicationDefaults
  Organizations:
  Policies: &ApplicationDefaultPolicies
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities: *ApplicationCapabilities

#Orderer
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.ifmprofile-network.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Capabilities: *OrdererCapabilities
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    # BlockValidation specifies what signatures must be included in the block
    # from the orderer for the peer to validate it.
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    # Who may invoke the 'Deliver' API
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    # Who may invoke the 'Broadcast' API
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    # By default, who may modify elements at this config level
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities


#Profiles
Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      ProfileConsortium:
        Organizations:
          - *usb
          - *jpmc
          - *boa

  ProfileChannel:
    Consortium: ProfileConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *usb
        - *jpmc
        - *boa
      Capabilities:
        <<: *ApplicationCapabilities
