version: '2'

volumes:
  orderer.ifmprofile-network.com:
  peer0.usb.ifmprofile-network.com:
  peer1.usb.ifmprofile-network.com:
  peer0.jpmc.ifmprofile-network.com:
  peer1.jpmc.ifmprofile-network.com:
  peer0.boa.ifmprofile-network.com:
  peer1.boa.ifmprofile-network.com:

networks:
  ifmprofile:

services:

  ca.usb.ifmprofile-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.usb.ifmprofile-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.usb.ifmprofile-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/754fccf4ad3f6a483161cf597b79fbdbdadaf1ee2f024e79da8c8e9b8bfb6dcb_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.usb.ifmprofile-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/754fccf4ad3f6a483161cf597b79fbdbdadaf1ee2f024e79da8c8e9b8bfb6dcb_sk
    volumes:
      - ./crypto-config/peerOrganizations/usb.ifmprofile-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.usb.ifmprofile-network.com
    networks:
      - ifmprofile

  ca.jpmc.ifmprofile-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.jpmc.ifmprofile-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.jpmc.ifmprofile-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.jpmc.ifmprofile-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    volumes:
      - ./crypto-config/peerOrganizations/jpmc.ifmprofile-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.jpmc.ifmprofile-network.com
    networks:
      - ifmprofile

  ca.boa.ifmprofile-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.boa.ifmprofile-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.boa.ifmprofile-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9ed31fcf7a2fd649ac2e52254a041e4244dca899f86e6532789601c6fe18a019_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.boa.ifmprofile-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/9ed31fcf7a2fd649ac2e52254a041e4244dca899f86e6532789601c6fe18a019_sk
    volumes:
      - ./crypto-config/peerOrganizations/boa.ifmprofile-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.boa.ifmprofile-network.com
    networks:
      - ifmprofile

  orderer.ifmprofile-network.com:
    extends:
      file:   docker-base/docker-compose-base.yaml
      service: orderer.ifmprofile-network.com
    container_name: orderer.ifmprofile-network.com
    networks:
      - ifmprofile

  peer0.usb.ifmprofile-network.com:
    container_name: peer0.usb.ifmprofile-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.usb.ifmprofile-network.com
    networks:
      - ifmprofile

  peer1.usb.ifmprofile-network.com:
    container_name: peer1.usb.ifmprofile-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.usb.ifmprofile-network.com
    networks:
      - ifmprofile

  peer0.jpmc.ifmprofile-network.com:
    container_name: peer0.jpmc.ifmprofile-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.jpmc.ifmprofile-network.com
    networks:
      - ifmprofile

  peer1.jpmc.ifmprofile-network.com:
    container_name: peer1.jpmc.ifmprofile-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.jpmc.ifmprofile-network.com
    networks:
      - ifmprofile

  peer0.boa.ifmprofile-network.com:
    container_name: peer0.boa.ifmprofile-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.boa.ifmprofile-network.com
    networks:
      - ifmprofile

  peer1.boa.ifmprofile-network.com:
    container_name: peer1.boa.ifmprofile-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.boa.ifmprofile-network.com
    networks:
      - ifmprofile

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.usb.ifmprofile-network.com:7051
      - CORE_PEER_LOCALMSPID=usbMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/usb.ifmprofile-network.com/peers/peer0.usb.ifmprofile-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/usb.ifmprofile-network.com/peers/peer0.usb.ifmprofile-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/usb.ifmprofile-network.com/peers/peer0.usb.ifmprofile-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/usb.ifmprofile-network.com/users/Admin@usb.ifmprofile-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
    #  - ./../chaincode-advanced/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode-advanced/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.usb.ifmprofile-network.com
      - ca.jpmc.ifmprofile-network.com
      - ca.boa.ifmprofile-network.com
      - orderer.ifmprofile-network.com
      - peer0.usb.ifmprofile-network.com
      - peer1.usb.ifmprofile-network.com
      - peer0.jpmc.ifmprofile-network.com
      - peer1.jpmc.ifmprofile-network.com
      - peer0.boa.ifmprofile-network.com
      - peer1.boa.ifmprofile-network.com
    networks:
      - ifmprofile

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv:latest
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=peer0.usb.ifmprofile-network.com:7051
      - CORE_PEER_LOCALMSPID=usbMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/usb.ifmprofile-network.com/users/Admin@usb.ifmprofile-network.com/msp
      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/crypto/peerOrganizations/usb.ifmprofile-network.com/users/Admin@usb.ifmprofile-network.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/crypto/peerOrganizations/usb.ifmprofile-network.com/users/Admin@usb.ifmprofile-network.com/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/crypto/peerOrganizations/usb.ifmprofile-network.com/users/Admin@usb.ifmprofile-network.com/tls/ca.crt
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode:/opt/gopath/src/chaincode
     # - ./../chaincode-advanced:/opt/gopath/src/chaincode-advanced
      - ./crypto-config:/opt/gopath/src/crypto
    networks:
      - ifmprofile

